language: node_js
sudo: true
node_js:
  - "7.9.0"
install:
  - npm install
script:
  - npm test
after_success:
  - npm run coverage
  "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"